### ISSUE TITLE
1주차 세미나

### ISSUE THREAD

**Issue by HELLOHIDI** [GO-SOPT-iOS-Part/HELLOHIDI#1]
## 🛠 Issue
- 1주차 세미나

## 📋 To-do
- [ ] 속성 추가해서 뷰 완성하기
- [ ] final 키워드를 왜 사용할까요? 성능적 이점에는 무엇이 있을까요?
- [ ] private 키워드를 왜 사용할까요?
- [ ] lazy var, let으로 프로퍼티를 선언하였는데 둘의 차이점은 무엇일까요?
- [ ] ViewController의 생명주기는 구냥 복습해주세요! 굉장히 중요하답니다!
- [ ] forEach와 $0는 무엇일까요?
- [ ] $0.translatesAutoresizingMaskIntoConstraints = false 는 왜 작성한 것일까요?
