### ISSUE TITLE
[Feat] TVING Auto Layout 및 기능 구현

### ISSUE THREAD

**Issue by HELLOHIDI** [GO-SOPT-iOS-Part/HELLOHIDI#3]
## 🛠 Issue
- TVING Auto Layout 및 기능 구현

## 📋 To-do
- [ ] Auto Layout 잡기
- [ ] 아이디, 비밀번호 텍스트필드 각각 활성화되었을 때 border 컬러 수정
- [ ] 아이디, 비밀번호 텍스트필드의 텍스트가 !isEmpty일 때 버튼을 활성화
- [ ] 활성화 된 로그인하기 버튼을 클릭했을 때, 아이디를 데이터 전달
- [ ] 비밀번호 텍스트필드 default 값은 security가 적용
- [ ] 눈 모양 버튼을 클릭 시, security를 해제
- [ ] 글 삭제 버튼을 클릭 시, 아이디, 비밀번호 텍스트필드를 각각 클리어
- [ ] 정규식 추가
