### ISSUE TITLE
[Feat] 데이터 전달 방식 연습

### ISSUE THREAD

**Issue by HELLOHIDI** [GO-SOPT-iOS-Part/HELLOHIDI#7]
## 🛠 Issue
- 데이터 전달 방식 연습

## 📋 To-do
- [ ] dataBind 함수 연습
- [ ] protocol-delegate 패턴 연습
- [ ] closure 전달 연습
- [ ] NotificationCenter 전달 연습
